/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "LambdaAuth": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "LambdaAuthApi": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "LambdaAuthTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "MyBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "MyPostgres": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Postgres"
      "username": string
    }
    "MyVpc": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
    "MyWeb": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "QueryApi": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
  }
}
